<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class NewsUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
			'title' => ['required', 'string', 'min:3', 'max:50'],
			'text'  => ['required', 'string', 'max:200']
        ];
    }

    public function messages()
	{
		return parent::messages(); // TODO: Change the autogenerated stub
	}
	public function attributes()
	{
		return [
			 'title' => 'новость'
		];
	}
}
